name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs: 
  check-application: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: 1.24
      - run: go test
      - run: go run math.go
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: lfgambabr/full.002.ci:latest